### ISSUE TITLE
Add default factories list to a plugin defaults

### ISSUE THREAD

**Issue by sergeysova** [effector/swc-plugin-legacy#10]
Just use the list from:

https://github.com/effector/effector/blob/87cef761c897c3139188b018b2f186112ac914a4/src/babel/babel-plugin.js#L548-L559

**Comment by igorkamyshev** [comment]
Already done in https://github.com/effector/swc-plugin/commit/f3b2984f963a53aef9c8b5f25d6ad7cb02e89dd3
