### ISSUE TITLE
Sids incorrectly set for multiple factories call

### ISSUE THREAD

**Issue by domosedov** [effector/swc-plugin-legacy#11]
Reproduce:
https://github.com/domosedov/nextjs_effector_swc_plugin

We have three factories call:

```ts
export const $s1 = status({ effect: fx1 });
export const $s2 = status({ effect: fx1 });
export const $s3 = status({ effect: fx1 });

console.log("[Status sids]:", $s1.sid, $s2.sid, $s3.sid); // => 1f446qz3w08n4|abrgim abrgim abrgim
```

But we have prefix only for the first `status` call

После каждого изменения `next.config.js`, рекомендую удалять папку `.next`

**Comment by eaglus** [comment]
@Drevoed 
Он второй раз не воспринимает фабрику, потому что тут есть проверка на  `is_factory.contains(&ident.to_id())` - https://github.com/effector/swc-plugin/blame/main/src/effector.rs#L982

Ниже он идентификатор удаляет и из хеша factory_map.

https://github.com/effector/swc-plugin/blame/main/src/effector.rs#L863
Вот тут он идентификатор фабрики добавляет в factory_map, а после первого вызова почему-то удаляет

Это сделано для вложенного вызова fn - чтобы там сиды не делать?

```js
const x1 = _withFactory$0({
    sid: "dad5qdcygwg6",
    fn: ()=>createFactory(123),
```

Но не лучше ли тогда просто сделать временную переменную перед вызовом withFactory?
И эта защита не нужна будет, и будут работать вложенные варианты типа такого

```js
import createFactory from './factory';

const x1 = createFactory(123, createFactory(456)); //почему бы фабрике не хотеть какой-нибудь юнит в качестве параметра?
```

**Comment by eaglus** [comment]
@Drevoed  @AlexandrHoroshih @sergeysova @domosedov Please review my fix

**Comment by sergeysova** [comment]
> Это сделано для вложенного вызова fn - чтобы там сиды не делать?

По идее вложенные вызовы фабрик тоже должны получать свои sid'ы. Вполне можно вкладывать и withFactory в таком раскладе.

Но остается вопрос, что делать в таком кейсе:

```ts
import createFactory from './factory';

const x1 = createFactory(123, createFactory(456));
```

Ведь если вкладывать, то получится:

```ts
const x1 = _withFactory$0({
    sid: "dad5qdcygwg6",
    fn: () => createFactory(123, _withFactory$0({
	    sid: "76td7f6std7f",
	    fn: () => createFactory(456),
	}),
});
```

Но сиды будут расставлены возможно не так, как ожидалось:

```
456 — "dad5qdcygwg6|76td7f6std7f"
123 — "dad5qdcygwg6"
```

Тогда как ожидалось, что вложенности не будет.

```
456 — "76td7f6std7f"
123 — "dad5qdcygwg6"
```

---

Я думаю, что наиболее очевидный вариант, без вложенности. Ведь второй вызов фабрики не находится "внутри" первой фабрики. В этом случае у нас должен быть примерно вот такой код:

```ts

const _fctry0 = _withFactory$0({
    sid: "76td7f6std7f",
    fn: () => createFactory(456),
})

const x1 = _withFactory$0({
    sid: "dad5qdcygwg6",
    fn: () => createFactory(123, _fctry0),
});
```

Фабрика 456 и так и так будет вызвана раньше, чем 123. Зато вложенности sid'ов не будет.

**Comment by eaglus** [comment]
@sergeysova  @Drevoed @AlexandrHoroshih 

> По идее вложенные вызовы фабрик тоже должны получать свои sid'ы. Вполне можно вкладывать и withFactory в таком раскладе.

У меня в pr так и сделано - я сначала обрабатываю ноду (visit_mut_children_with), и там все вложенные вызовы фабрик обрабатываются, а потом уже заменяю ноду на вызов withFactory.
И зацикливания не получается, и не надо переменных никаких делать.

Вот: https://github.com/effector/swc-plugin/pull/30/files#diff-de48c5958bbe008754ed534eea77cfda0b3b8c5c0644b738cb22fdaf76b87dc2R999

**Comment by eaglus** [comment]
@sergeysova 

> Фабрика 456 и так и так будет вызвана раньше, чем 123. Зато вложенности sid'ов не будет.

А что плохого во вложенных вызовах фабрик?

https://github.com/effector/swc-plugin/pull/30/files#diff-bd9683d58394331f891891485d4d12ea67adc0a52c768cf6a687e6c7cc6caeb2R49

Каждая фабрика вызывается только один раз, со своим сидом, сиды стабильные.

Зачем эти вложенные вызовы фабрик вытаскивать в отдельные переменные?

**Comment by sergeysova** [comment]
> Зачем эти вложенные вызовы фабрик вытаскивать в отдельные переменные?

А зачем вложенные сиды там, где они не нужны?

**Comment by eaglus** [comment]
> > Зачем эти вложенные вызовы фабрик вытаскивать в отдельные переменные?
> 
> А зачем вложенные сиды там, где они не нужны?

@sergeysova 
А как без них? И это не сиды вложенные, а вызовы фабрик вложенные, в качестве аргументов. 
Они в коде есть, плагин же не может это игнорировать.
Если мне убирать вложенные вызовы фабрик, и выносить их в переменные (вместо того, чтоб оставить их в аргументах), то мне надо это выражение обходить рекурсивно, заносить в плоский список эти узлы, которые надо будет вынести в переменные состояния, потом чистить их непонятно когда...
И зачем этот геморрой?
Я в этом pr вообще обошелся без состояния.

А если там условия в аргументах?
```
const someStore$ = someFactory(123, someCondition ? someFactory2() : someFactory3());  
```
и вот как всё это обработать, если не следовать структуре кода, и не оставлять вложенные вызовы фабрик-аргументов?

я не хочу менять структуру кода - это сильно всё усложняет, и багов добавляет.

**Comment by eaglus** [comment]
@sergeysova 

```
456 — "dad5qdcygwg6|76td7f6std7f"
123 — "dad5qdcygwg6"
```
я не понимаю, откуда у вызова фабрики для 456 возьмётся такой сид составной.

вот же - у фабрики 123 сид будет dad5qdcygwg6, а у 456 - 76td7f6std7f.

там же withFactory вызываются именно с этими параметрами

```
const x1 = _withFactory$0({
    sid: "dad5qdcygwg6",
    fn: () => createFactory(123, _withFactory$0({
	    sid: "76td7f6std7f",
	    fn: () => createFactory(456),
	}),
});
```

и я не понимаю, что значит вложенность сида. 
там же оба сида сами по себе живут и передаются  в фабрики.

ну делает одна фабрика аргумент для другой, и что тут такого?

где тут связь параметров (сидов) этих фабрик?

**Comment by eaglus** [comment]
@sergeysova 
Вот в бабель-плагине:

Вот вложенный вызов фабрики **AnotherImport** (аргумент condition у фабрики **Defaulting**).
https://github.com/effector/effector/blob/master/src/babel/__tests__/fixtures/factories-only-with-name.js#L8

Вот после плагина вложенный вызов остаётся:
https://github.com/effector/effector/blob/master/src/babel/__tests__/__snapshots__/babel-plugin.test.js.snap#L2144

**Comment by domosedov** [comment]
когда ПР с фиксом заапрувят?

**Comment by sergeysova** [comment]
@domosedov это надо ждать @Drevoed

**Comment by eaglus** [comment]
@sergeysova @Drevoed @AlexandrHoroshih  а кто-нибудь другой может pr принять?

**Comment by Drevoed** [comment]
Спасибо за пр, сегодня посмотрю
