### ISSUE TITLE
Bug(nextjs): dev mode breaks after update to 0.0.8 

### ISSUE THREAD

**Issue by domosedov** [effector/swc-plugin-legacy#16]
update plugin 0.0.7 -> 0.0.8
https://github.com/domosedov/nextjs_effector_swc_plugin
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /Users/k.mironov/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.37/src/impls/core/mod.rs:265:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/domosedov/Dev/sandbox/nextjs_effector_swc_plugin/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/dev/amp-dev.js")'

...long stacktrace
```

**Comment by Drevoed** [comment]
Here's an issue that you can upvote on an upstream: https://github.com/swc-project/swc/issues/6807.

Our hands are tied by SWC for now.

**Comment by Drevoed** [comment]
Should be fixed by #26.

Can you please try it out?

**Comment by domosedov** [comment]
> Should be fixed by #26.
> 
> Can you please try it out?

Works with latest version Next.js
```
"next": "13.1.4"
"@effector/swc-plugin": "0.0.9"
```

**Comment by domosedov** [comment]
<img width="518" alt="Снимок экрана 2023-01-24 в 10 35 15" src="https://user-images.githubusercontent.com/42298502/214236076-d51097c3-9083-491a-adaa-0018803f34bc.png">

**Comment by Drevoed** [comment]
Yeah, sids fix is planned for next release and tracked in another issue #11 .
