### ISSUE TITLE
Plugin conflicts when transforms code like "someDomain.domain" when there is var with name "domain"

### ISSUE THREAD

**Issue by eaglus** [effector/swc-plugin-legacy#21]
`import {createDomain} from "effector";

const domain = createDomain();
const someDomain = createDomain();

const domainInner = someDomain.domain('inner domain');
`

transforms to

`import { createDomain } from "effector";
var _effectorFileName$0 = "/output.js";
const domain = createDomain({
    sid: "miml62lu5xv6",
    loc: {
        file: _effectorFileName$0,
        line: 3,
        column: 15
    },
    name: "domain"
});
const someDomain = createDomain({
    sid: "11zm8yzuqbfkt",
    loc: {
        file: _effectorFileName$0,
        line: 4,
        column: 19
    },
    name: "someDomain"
});
const domainInner = someDomain.domain('inner domain');
`

someDomain has method "domain" same as local/global variable "domain".
because of this code: https://github.com/effector/swc-plugin/blob/main/src/effector.rs#L944

plugin does not have to set "local" var here (for method), it should not check method name for local variables

https://github.com/effector/swc-plugin/blob/3088a9a3f1db57ac386f1c677169e20d4c112dde/src/effector.rs#L372

Also, line number (state.loc) is not updated in domain method code:

Here we need to update state.loc:
https://github.com/effector/swc-plugin/blob/3088a9a3f1db57ac386f1c677169e20d4c112dde/src/effector.rs#L941

**Comment by Drevoed** [comment]
Fixed by #22.
